services:
  backend:
    build:
      context: ./backend
      dockerfile: backend.Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    networks:
      - app-network


  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command: cloudflared tunnel --config cloudflare-tunnel.yml run
    volumes:
      - ./cloudflared:/etc/cloudflared
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network: