

FISH = [
    # Common
    {
        "id": 1,
        "name": "Codfish",
        "rarity": "Common",
        "depth": "surface",
        "fact": "A cold-water staple prized for its flaky white meat.",
        "color": "#7BC67E",
        "sprite": "codfish.png",
        "location_id": 1,
    },
    {
        "id": 2,
        "name": "Herring",
        "rarity": "Common",
        "depth": "surface",
        "fact": "A small schooling fish that sustains larger predators.",
        "color": "#89CFF0",
        "sprite": "Herring.png",
        "location_id": 1,
    },
    {
        "id": 3,
        "name": "Perch",
        "rarity": "Common",
        "depth": "mid",
        "fact": "A freshwater fish known for its bold vertical stripes.",
        "color": "#F4A460",
        "sprite": "perch.png",
        "location_id": 2,
    },
    {
        "id": 4,
        "name": "Carp",
        "rarity": "Common",
        "depth": "mid",
        "fact": "A hardy species that can live for decades in calm waters.",
        "color": "#DAA520",
        "sprite": "carp.png",
        "location_id": 1,
    },
    {
        "id": 20,
        "name": "Bream",
        "rarity": "Common",
        "depth": "mid",
        "fact": "A bottom feeder often found near rocky reefs.",
        "color": "#C0C0A8",
        "sprite": "bream.png",
        "location_id": 4,
    },
    {
        "id": 23,
        "name": "Turbot",
        "rarity": "Common",
        "depth": "deep",
        "fact": "A flatfish prized by chefs for its delicate flavor.",
        "color": "#B0C4DE",
        "sprite": "turbot.png",
        "location_id": 5,
    },

    # Uncommon
    {
        "id": 5,
        "name": "Salmon",
        "rarity": "Uncommon",
        "depth": "mid",
        "fact": "Swims upstream to spawn where it was born.",
        "color": "#FA8072",
        "sprite": "salmon.png",
        "location_id": 1,
    },
    {
        "id": 6,
        "name": "Pike",
        "rarity": "Uncommon",
        "depth": "mid",
        "fact": "An aggressive predator with razor-sharp teeth.",
        "color": "#6B8E23",
        "sprite": "pike.png",
        "location_id": 2,
    },
    {
        "id": 7,
        "name": "Catfish",
        "rarity": "Uncommon",
        "depth": "deep",
        "fact": "Uses whisker-like barbels to sense food in muddy water.",
        "color": "#808080",
        "sprite": "catfish.png",
        "location_id": 2,
    },
    {
        "id": 8,
        "name": "Swordfish",
        "rarity": "Rare",
        "depth": "deep",
        "fact": "Can swim at speeds of up to 97 km/h.",
        "color": "#4169E1",
        "sprite": "swordfish.png",
        "location_id": 2,
    },
    {
        "id": 15,
        "name": "Anglerfish",
        "rarity": "Rare",
        "depth": "deep",
        "fact": "A deep-sea ambush predator with a glowing lure.",
        "color": "#2F4F4F",
        "sprite": "anglerfish.png",
        "location_id": 2,
    },

    # Caribbean
    {
        "id": 13,
        "name": "Clownfish",
        "rarity": "Common",
        "depth": "mid",
        "fact": "Lives among sea anemones and bright coral reefs.",
        "color": "#FF8C00",
        "sprite": "clownfish.png",
        "location_id": 3,
    },
    {
        "id": 17,
        "name": "Parrotfish",
        "rarity": "Common",
        "depth": "mid",
        "fact": "Uses its beak-like mouth to scrape algae from coral.",
        "color": "#32CD32",
        "sprite": "parrotfish.png",
        "location_id": 3,
    },
    {
        "id": 18,
        "name": "Blue Tang",
        "rarity": "Uncommon",
        "depth": "mid",
        "fact": "A bright reef fish known for its vivid blue body.",
        "color": "#1552AF",
        "sprite": "bluetang.png",
        "location_id": 3,
    },
    {
        "id": 19,
        "name": "Blue Marlin",
        "rarity": "Uncommon",
        "depth": "mid",
        "fact": "A powerful game fish prized for speed and strength.",
        "color": "#1E90FF",
        "sprite": "BlueMarlin.png",
        "location_id": 4,
    },
    {
        "id": 21,
        "name": "Mahi Mahi",
        "rarity": "Uncommon",
        "depth": "surface",
        "fact": "A colorful open-ocean fish famed for its fast bursts.",
        "color": "#66CDAA",
        "sprite": "MahiMahi.png",
        "location_id": 5,
    },
    {
        "id": 22,
        "name": "Lionfish",
        "rarity": "Uncommon",
        "depth": "mid",
        "fact": "A venomous reef dweller with feathery fins.",
        "color": "#FF4500",
        "sprite": "lionfish.png",
        "location_id": 3,
    },
    {
        "id": 14,
        "name": "Barracuda",
        "rarity": "Uncommon",
        "depth": "mid",
        "fact": "A sleek hunter known for its speed and sharp teeth.",
        "color": "#DAA520",
        "sprite": "barracuda.png",
        "location_id": 3,
    },

    # Pacific Ocean
    {
        "id": 16,
        "name": "Great White Shark",
        "rarity": "Legendary",
        "depth": "surface",
        "fact": "A top predator feared for its powerful bite.",
        "color": "#D3D3D3",
        "sprite": "GreatWhite.png",
        "location_id": 2,
    },
    {
        "id": 25,
        "name": "Hammerhead Shark",
        "rarity": "Rare",
        "depth": "deep",
        "fact": "A distinctive shark with a wide, hammer-shaped head.",
        "color": "#2E8B57",
        "sprite": "hammerhead.png",
        "location_id": 4,
    },
    {
        "id": 26,
        "name": "Manta Ray",
        "rarity": "Rare",
        "depth": "deep",
        "fact": "A graceful, gentle giant that glides through open water.",
        "color": "#20B2AA",
        "sprite": "MantaRay.png",
        "location_id": 3,
    },
    {
        "id": 9,
        "name": "Oarfish",
        "rarity": "Rare",
        "depth": "deep",
        "fact": "The world's longest bony fish, reaching over 10 meters.",
        "color": "#C0C0C0",
        "sprite": "oarfish.png",
        "location_id": 1,
    },
    {
        "id": 24,
        "name": "Coelacanth",
        "rarity": "Rare",
        "depth": "deep",
        "fact": "A living fossil once thought extinct for millions of years.",
        "color": "#708090",
        "sprite": "Coelacanth.png",
        "location_id": 4,
    },
    {
        "id": 27,
        "name": "Squid",
        "rarity": "Legendary",
        "depth": "deep",
        "fact": "A quick cephalopod that jets away with a cloud of ink.",
        "color": "#6A5ACD",
        "sprite": "squid.png",
        "location_id": 5,
    },

    # Mariana Trench
    {
        "id": 11,
        "name": "Golden Koi",
        "rarity": "Legendary",
        "depth": "deep",
        "fact": "A prized ornamental fish with shimmering scales.",
        "color": "#FFD700",
        "sprite": "golden.png",
        "location_id": 1,
    },
    {
        "id": 28,
        "name": "Mythical Fish",
        "rarity": "Legendary",
        "depth": "deep",
        "fact": "A fabled creature whispered about by fishermen.",
        "color": "#9B59B6",
        "sprite": "Mythical.png",
        "location_id": 4,
    },
]




# Quick lookup by id
FISH_BY_ID = {f["id"]: f for f in FISH}

# Mystery fish — one per location
MYSTERY_FISH = [
    {
        "id": 101,
        "name": "Baltic Ghost",
        "location_id": 1,
        "rarity": "Location Legend",
        "depth": "deep",
        "fact": "A ghostly creature said to haunt the Baltic Sea.",
        "color": "#A0C4FF",
        "sprite": "ghost.png",  
    },
    {
        "id": 102,
        "name": "North Sea Titan",
        "location_id": 2,
        "rarity": "Location Legend",
        "depth": "deep",
        "fact": "A massive beast lurking in the depths of the North Sea.",
        "color": "#6B8CFF",
        "sprite": "titan.png",
    },
    {
        "id": 103,
        "name": "Caribbean Phantom",
        "location_id": 3,
        "rarity": "Location Legend",
        "depth": "deep",
        "fact": "Spotted only once, by a sailor who never spoke again.",
        "color": "#FF6B6B",
        "sprite": "phantom.png",
    },
    {
        "id": 104,
        "name": "Pacific Leviathan",
        "location_id": 4,
        "rarity": "Location Legend",
        "depth": "deep",
        "fact": "So large it creates its own weather patterns.",
        "color": "#4ECDC4",
        "sprite": None,
    },
    {
        "id": 105,
        "name": "Trench God",
        "location_id": 5,
        "rarity": "Location Legend",
        "depth": "deep",
        "fact": "No one has seen it and lived to tell the tale.",
        "color": "#9B59B6",
        "sprite": None,
    },
    {
        "id": 106,
        "name": "Megalodon",
        "location_id": 5,
        "rarity": "Location Legend",
        "depth": "deep",
        "fact": "Largest shark to have ever lived.",
        "color": "#9B59B6",
        "sprite": "megalodon.png",
    },
]

MYSTERY_FISH_BY_LOCATION = {f["location_id"]: f for f in MYSTERY_FISH}

# Grouped by rarity
FISH_BY_RARITY = {
    "Common":    [f for f in FISH if f["rarity"] == "Common"],
    "Uncommon":  [f for f in FISH if f["rarity"] == "Uncommon"],
    "Rare":      [f for f in FISH if f["rarity"] == "Rare"],
    "Legendary": [f for f in FISH if f["rarity"] == "Legendary"],
}

LOCATIONS = [
    {
        "id":         1,
        "name":       "Baltic Sea",
        "unlock_at":  0,
        "water_top":  [0.10, 0.30, 0.25],
        "water_deep": [0.03, 0.12, 0.10],
    },
    {
        "id":         2,
        "name":       "North Sea",
        "unlock_at":  4,
        "water_top":  [0.08, 0.18, 0.35],
        "water_deep": [0.02, 0.08, 0.18],
    },
    {
        "id":         3,
        "name":       "Caribbean",
        "unlock_at":  8,
        "water_top":  [0.05, 0.45, 0.55],
        "water_deep": [0.02, 0.20, 0.35],
    },
    {
        "id":         4,
        "name":       "Pacific Ocean",
        "unlock_at":  14,
        "water_top":  [0.03, 0.12, 0.45],
        "water_deep": [0.01, 0.05, 0.20],
    },
    {
        "id":         5,
        "name":       "Mariana Trench",
        "unlock_at":  22,
        "water_top":  [0.02, 0.05, 0.15],
        "water_deep": [0.005, 0.01, 0.05],
    },
]

LOCATIONS_BY_ID = {l["id"]: l for l in LOCATIONS}